coffeescript:
  enabled: false
javascript:
  config_file: .jshintrc
  ignore_file: .jshintignore
jscs:
  enabled: false
  config_file: .jscsrc
python:
  enabled: true
  config_file: .flake8.ini
ruby:
  enabled: false
scss:
  enabled: false
