version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"
  fail_on_warning: true
formats: []
python:
  install:
    - requirements: requirements/docs.txt
