#!/bin/bash -e

function create_virtualenv() {
	echo "Creating virtualenv...";
	virtualenv --no-site-packages --distribute .;
	source bin/activate;
}

function maybe_create_virtualenv() {
	echo "
This script can create an isolated environment for installing python
software libraries needed for development. This setup is recommended.

If you are not familiar with using virtualenv [1] to manage a python
development environment you may wish to take a few minutes to read a
bit about it.

If you are comfortable managing it yourself, e.g. through a tool
like virtualenv-wrapper [2], you may decline to create one now.

[1] http://www.virtualenv.org/
[2] http://virtualenvwrapper.readthedocs.org/
"

	if [ -t 0 ]; then
		while true; do
			read -p "Create a virtualenv now (recommended)? " yn
			case $yn in
				[Yy]* )
					create_virtualenv
					break;;
				[Nn]* ) break;;
				* ) echo "Please answer yes or no.";;
			esac
		done
	else
		create_virtualenv
	fi
}

if test -z "$VIRTUAL_ENV"; then
	if test ! -e bin/activate; then
		maybe_create_virtualenv
	else
		source bin/activate
	fi
fi


if test -z "$PIP_DOWNLOAD_CACHE"; then
	export PIP_DOWNLOAD_CACHE=.pip
fi

echo "Ensuring an up-to-date pip..."
pip install -qU pip

echo "Checking dependencies..."
diff -q requirements.txt .installed.txt 2> /dev/null || {
	echo "Installing dependencies (this may take a few minutes)..."
	pip install -qr requirements.txt
	cp requirements.txt .installed.txt
}

echo -n "Checking for Compass..."
command -v compass || echo "...not found!"

echo -n "Checking for CoffeeScript..."
command -v coffee || echo "...not found!"


echo -n "Checking for CleanCSS..."
command -v cleancss || {
	echo "...not found!"
	echo
	echo "CleanCSS was not found. You MUST run in debug mode."
	echo "The development configuration does this."
	echo
}

echo -n "Checking for UglifyJS..."
command -v uglifyjs || {
	echo "...not found!"
	echo
	echo "UglifyJS was not found. You MUST run in debug mode."
	echo "The development configuration does this."
	echo
}
