#!/bin/sh -e

if test -z "$VIRTUAL_ENV"; then
	if test ! -e bin/activate; then
		echo "Creating virtualenv..."
		virtualenv --no-site-packages .
	fi
	echo "Entering virtualenv..."
	. bin/activate
fi

echo "Checking dependencies..."
if test ! -d build; then mkdir build; fi

diff_num=`pip freeze \
	| diff --suppress-common-lines -y - build/frozen.txt \
	| wc -l`

if test $diff_num -gt 1; then
	echo "Installing dependencies..."
	pip install -r requirements.txt 1>/dev/null
	pip freeze > build/frozen.txt &> /dev/null
fi

echo "Setting up development..."
python setup.py develop 1>/dev/null

echo -n "Checking for Compass..."
command -v compass || echo "...not found!"

echo -n "Checking for CoffeeScript..."
command -v coffee || echo "...not found!"

echo -n "Checking for Handlebars..."
command -v handlebars || echo "...not found!"

echo -n "Checking for UglifyJS..."
command -v uglifyjsbog|| {
	echo "...not found!"
	echo
	echo "You MUST run in debug mode."
	echo "The development configuration does this."
	echo
}
