#!/usr/bin/env python
from os import environ
from os.path import join
from sys import argv


if __name__ == '__main__':
    # If  a virtual environment is present make sure it's being used.
    virtual_env = environ.get('VIRTUAL_ENV', '.')
    activate = join(virtual_env, 'bin', 'activate_this.py')
    execfile(activate, dict(__file__=activate))

    from h.script import run
    run(argv[1:])
