#!/bin/sh
POSTGRES="gosu postgres"

$POSTGRES psql -c "ALTER USER $POSTGRES_USER SUPERUSER;"

$POSTGRES psql -c "CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER ;"
$POSTGRES psql -c "CREATE DATABASE "htest" OWNER $POSTGRES_USER ;"
