elasticsearch:
  image: hypothesis/elasticsearch:elasticsearch7.10
  ports:
    - '127.0.0.1:9200:9200'
  healthcheck:
      test: curl --fail --silent http://localhost:9200 >/dev/null
      interval: 3s
      start_period: 1m
  environment:
    - discovery.type=single-node
rabbit:
  image: rabbitmq:3.12-management-alpine
  ports:
    - '127.0.0.1:5672:5672'
    - '127.0.0.1:15672:15672'
