#!/bin/sh

set -eu

case "$ACTION" in
    gulp)
        npm install
        ;;
    extensions)
        pip install --use-wheel -e .
        npm install
        # trick the Makefile into skipping npm install
        touch node_modules/.uptodate
        ;;
esac
