#!/bin/sh

: ${TRAVIS_TAG:=}

set -eu

case "$ACTION" in
    tox)
        tox
        ;;
    gulp)
        gulp "$GULPTASK"
        ;;
    extensions)
        if [ -n "$TRAVIS_TAG" ]; then
            export SENTRY_RELEASE_VERSION=$(echo "$TRAVIS_TAG" | cut -dv -f2-)
            gulp build upload-sourcemaps
        fi
        make extensions
        ;;
esac
