FORMAT: 1A
HOST: https://hypothes.is

# Hypothes.is
[Hypothes.is](http://hypothes.is/) provides an implementation of the [Annotator](http://annotatorjs.org/)
Storage API.

## API Entry [/api]

### Retrieve service doc [GET]
+ Response 200 (application/json)

        {
          "message": "Annotator Store API",
          "links": {
            "search": {
              "desc": "Basic search API",
              "method": "GET",
              "url": "https://hypothes.is/api/search"
            },
            "annotation": {
              "create": {
                "desc": "Create a new annotation",
                "method": "POST",
                "url": "https://hypothes.is/api/annotations"
              },
              "update": {
                "desc": "Update an existing annotation",
                "method": "PUT",
                "url": "https://hypothes.is/api/annotations/:id"
              },
              "delete": {
                "desc": "Delete an annotation",
                "method": "DELETE",
                "url": "https://hypothes.is/api/annotations/:id"
              },
              "read": {
                "desc": "Get an existing annotation",
                "method": "GET",
                "url": "https://hypothes.is/api/annotations/:id"
              }
            }
          }
        }

## Annotation Collection [/api/annotations{?limit,offset}]

+ Model (application/json)

            [
              {
                "tags": [],
                "references": [
                  "iHNf1mBeTrS0ClW_2rF3Iw"
                ],
                "updated": "2015-02-05T16:54:00.156927+00:00",
                "created": "2015-02-05T15:54:59.597989+00:00",
                "text": "The 5 \"encouraging facts\" about climate change the author mentions are:\n\n> in the previous 15 years [...] we’re seeing about 90% less temperature rise than expected\n\n> Antarctic sea ice [...] is increasing\n\n> sea levels are rising, but the rise is not accelerating\n\n> a decrease in the world’s surface that has been afflicted by droughts since 1982\n\n> the trend for landfalling typhoons around the Philippines has declined \n",
                "permissions": {
                  "update": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "admin": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "delete": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                "id": "LM-oVYS-TvauHw7bLK7XTw",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:emvincent@hypothes.is"
              },
              {
                "tags": [
                  "reference needed"
                ],
                "document": {
                  "prism": {},
                  "title": [
                    "The Alarming Thing About Climate Alarmism"
                  ],
                  "link": [
                    {
                      "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                    },
                    {
                      "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                      "rel": "canonical",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "dc": {},
                  "eprints": {},
                  "facebook": {
                    "title": [
                      "The Alarming Thing About Climate Alarmism"
                    ],
                    "image": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                    ],
                    "description": [
                      "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                    ],
                    "url": [
                      "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                    ],
                    "image:width": [
                      "553"
                    ],
                    "locale": [
                      "en_US"
                    ],
                    "image:height": [
                      "369"
                    ],
                    "site_name": [
                      "WSJ"
                    ],
                    "type": [
                      "article"
                    ]
                  },
                  "twitter": {
                    "card": [
                      "summary_large_image"
                    ],
                    "title": [
                      "The Alarming Thing About Climate Alarmism"
                    ],
                    "image": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_D_20150201121817.jpg"
                    ],
                    "description": [
                      "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                    ],
                    "site": [
                      "@WSJ"
                    ],
                    "domain": [
                      "wsj.com"
                    ],
                    "image:src": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                    ]
                  }
                },
                "updated": "2015-02-05T16:52:50.441027+00:00",
                "created": "2015-02-05T15:53:15.924190+00:00",
                "text": "This is a strong claim; a strong reference would be needed to back it up.\nIn this article, the author provides 5 facts about the changing climate to back this assertion. This is far from sufficient to give credit to the author's claim, especially since several of these facts are only one aspect of the story, as shown by the scientists' comments below.\n\n",
                "permissions": {
                  "update": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "admin": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "delete": [
                    "acct:emvincent@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 258,
                        "startContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]",
                        "startOffset": 217,
                        "type": "RangeSelector",
                        "endContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]"
                      },
                      {
                        "end": 587,
                        "start": 546,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "han expected. This ignores that",
                        "type": "TextQuoteSelector",
                        "suffix": ". The latest study from the Unit",
                        "exact": "much of the data are actually encouraging"
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 19,
                      "top": 442
                    },
                    "source": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "iHNf1mBeTrS0ClW_2rF3Iw",
                "user": "acct:emvincent@hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": [
                    "The Alarming Thing About Climate Alarmism"
                  ],
                  "link": [
                    {
                      "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                    },
                    {
                      "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                      "rel": "canonical",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "dc": {},
                  "eprints": {},
                  "facebook": {
                    "title": [
                      "The Alarming Thing About Climate Alarmism"
                    ],
                    "image": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                    ],
                    "description": [
                      "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                    ],
                    "url": [
                      "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                    ],
                    "image:width": [
                      "553"
                    ],
                    "locale": [
                      "en_US"
                    ],
                    "image:height": [
                      "369"
                    ],
                    "type": [
                      "article"
                    ],
                    "site_name": [
                      "WSJ"
                    ]
                  },
                  "twitter": {
                    "card": [
                      "summary_large_image"
                    ],
                    "title": [
                      "The Alarming Thing About Climate Alarmism"
                    ],
                    "image": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_D_20150201121817.jpg"
                    ],
                    "description": [
                      "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                    ],
                    "site": [
                      "@WSJ"
                    ],
                    "domain": [
                      "wsj.com"
                    ],
                    "image:src": [
                      "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                    ]
                  }
                },
                "updated": "2015-02-05T16:39:21.987184+00:00",
                "created": "2015-02-03T23:26:29.974141+00:00",
                "text": "This is true but somewhat misleading. \nOne can find 15-year periods earlier in the record when temperatures went up somewhat faster than projected. ",
                "permissions": {
                  "update": [
                    "acct:emanuel@hypothes.is"
                  ],
                  "admin": [
                    "acct:emanuel@hypothes.is"
                  ],
                  "delete": [
                    "acct:emanuel@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 426,
                        "startContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]",
                        "startOffset": 260,
                        "type": "RangeSelector",
                        "endContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]"
                      },
                      {
                        "end": 755,
                        "start": 589,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "data are actually encouraging.",
                        "type": "TextQuoteSelector",
                        "suffix": "The average of all models expec",
                        "exact": "The latest study from the United Nations Intergovernmental Panel on Climate Change found that in the previous 15 years temperatures had risen 0.09 degrees Fahrenheit."
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 47,
                      "top": 442
                    },
                    "source": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "chAmdc_eQf-hSDKKzC5NuQ",
                "user": "acct:emanuel@hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": [
                    "Wer ist Pegida?: Dürfen wir vorstellen: Die Freunde von Pegida"
                  ],
                  "link": [
                    {
                      "href": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                    },
                    {
                      "href": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten",
                      "rel": "canonical",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "favicon": "http://images.zeit.de/static/img/favicon.ico",
                  "dc": {},
                  "eprints": {},
                  "facebook": {
                    "title": [
                      "Wer ist Pegida?: Dürfen wir vorstellen: Die Freunde von Pegida"
                    ],
                    "image": [
                      "http://images.zeit.de/gesellschaft/2015-02/pegida-dresden/pegida-dresden-540x304.jpg"
                    ],
                    "description": [
                      "Wer bekennt sich zu Pegida? Keiner weiß es genau. Auf Facebook aber sprechen die Anhänger der Bewegung. Diese Grafiken zeigen, was Pegidisten ausmacht"
                    ],
                    "url": [
                      "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                    ],
                    "type": [
                      "article"
                    ],
                    "site_name": [
                      "ZEIT ONLINE"
                    ]
                  },
                  "twitter": {}
                },
                "updated": "2015-02-05T15:48:35.699828+00:00",
                "created": "2015-02-05T15:48:35.699811+00:00",
                "text": "testing this real quick",
                "permissions": {
                  "update": [
                    "acct:fabianmu@hypothes.is"
                  ],
                  "admin": [
                    "acct:fabianmu@hypothes.is"
                  ],
                  "delete": [
                    "acct:fabianmu@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 26,
                        "startContainer": "/div[2]/div[2]/div[2]/div[1]/div[1]/p[1]",
                        "startOffset": 0,
                        "type": "RangeSelector",
                        "endContainer": "/div[2]/div[2]/div[2]/div[1]/div[1]/p[1]"
                      },
                      {
                        "end": 483,
                        "start": 457,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "stellen: Die Freunde von Pegida",
                        "type": "TextQuoteSelector",
                        "suffix": "? Keiner weiß es genau. Auf Face",
                        "exact": "Wer bekennt sich zu Pegida"
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 25,
                      "top": 333
                    },
                    "source": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "nLetVBXJReC1oZFaKIiN-A",
                "user": "acct:fabianmu@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "rsMTUkq5SqaqPq4frw6rVA",
                  "h5ZKl5MyQGiChvMvLHrWIQ",
                  "MMRtCKbZQw6xJ9Je9mw6oA"
                ],
                "updated": "2015-02-05T15:27:30.278992+00:00",
                "created": "2015-02-05T15:27:30.278960+00:00",
                "text": "Thanks for your reply.  (See https://hypothes.is/a/8DBwmnIhQ5mNY_qwZ7IbJQ.)  Given your passion for the subject, I encourage you to post also in the NYT comments.",
                "permissions": {
                  "update": [
                    "acct:rdhyee@hypothes.is"
                  ],
                  "admin": [
                    "acct:rdhyee@hypothes.is"
                  ],
                  "delete": [
                    "acct:rdhyee@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://well.blogs.nytimes.com/2015/02/03/new-york-attorney-general-targets-supplements-at-major-retailers/?hp&action=click&pgtype=Homepage&module=first-column-region&region=top-news&WT.nav=top-news&_r=0",
                "id": "JMOvXYPfTQ6tmrvS1Mq8kA",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:rdhyee@hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": "",
                  "link": [
                    {
                      "href": "http://hypothes.is/"
                    },
                    {
                      "href": "https://hypothes.is/",
                      "rel": "canonical",
                      "type": ""
                    },
                    {
                      "href": "https://hypothes.is/?p=238",
                      "rel": "shortlink",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                  "dc": {},
                  "eprints": {},
                  "facebook": {},
                  "twitter": {}
                },
                "updated": "2015-02-05T15:15:18.080929+00:00",
                "created": "2015-02-05T15:15:18.080897+00:00",
                "text": "Teeees",
                "permissions": {
                  "update": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "admin": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "delete": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://hypothes.is/",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 10,
                        "startContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]",
                        "startOffset": 0,
                        "type": "RangeSelector",
                        "endContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]"
                      },
                      {
                        "end": 2497,
                        "start": 2487,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "th in-situ feedback about th...",
                        "type": "TextQuoteSelector",
                        "suffix": "Google Analytics Typekit by Ado",
                        "exact": "Read more…"
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 18,
                      "top": 2057.600003051758
                    },
                    "source": "http://hypothes.is/"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "iiuopaJOSp6mLqy3FN66iw",
                "user": "acct:ujvari@stage.hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": "",
                  "link": [
                    {
                      "href": "http://hypothes.is/"
                    },
                    {
                      "href": "https://hypothes.is/",
                      "rel": "canonical",
                      "type": ""
                    },
                    {
                      "href": "https://hypothes.is/?p=238",
                      "rel": "shortlink",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                  "dc": {},
                  "eprints": {},
                  "facebook": {},
                  "twitter": {}
                },
                "updated": "2015-02-05T15:11:55.455988+00:00",
                "created": "2015-02-05T15:11:55.455971+00:00",
                "text": "Atom teszt",
                "permissions": {
                  "update": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "admin": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "delete": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://hypothes.is/",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 10,
                        "startContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]",
                        "startOffset": 0,
                        "type": "RangeSelector",
                        "endContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]"
                      },
                      {
                        "end": 2497,
                        "start": 2487,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "th in-situ feedback about th...",
                        "type": "TextQuoteSelector",
                        "suffix": "Google Analytics Typekit by Ado",
                        "exact": "Read more…"
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 18,
                      "top": 2057.6
                    },
                    "source": "http://hypothes.is/"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "X1B654lxS_uegUvc7dol5A",
                "user": "acct:ujvari@stage.hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "MVnP035EQ02sRmgnW5Xs9w"
                ],
                "updated": "2015-02-05T15:11:26.575324+00:00",
                "created": "2015-02-05T15:11:26.575292+00:00",
                "text": "Interesting that both you and Nairi asked \"how can we fix the parent info problem?\" This is what I was thinking a few years ago when my Trinity collaborators and I created the \"SmartChoices\" school search tool and researched how parents used and interpreted it. We'll read it later this semester.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                "id": "3v4FzkdPRbiV9L0geCJZmQ",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "Rj1pW-BWSBSPuMCY3LtExQ"
                ],
                "updated": "2015-02-05T15:10:57.045959+00:00",
                "created": "2015-02-05T15:10:57.045927+00:00",
                "text": "Interesting that both you and Rachel asked \"how can we fix the parent info problem\"? This is what I was thinking a few years ago when my Trinity collaborators and I created the \"SmartChoices\" school search tool and researched how parents used and interpreted it. We'll read it later this semester.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                "id": "4AxZec3hRPuj9alVWWt9qQ",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "S_462UK5Tdq-1ARY_zRCRg"
                ],
                "updated": "2015-02-05T15:07:18.607194+00:00",
                "created": "2015-02-05T15:07:18.607165+00:00",
                "text": "Great way to reframe the question here. You're making me think more deeply about Lubienski's chapter.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                "id": "sLADPndUSKa0Ucq0-jhgaw",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "2hxqJSZ2Qu6P7ZTJG6oW2Q"
                ],
                "updated": "2015-02-05T15:05:04.609382+00:00",
                "created": "2015-02-05T15:05:04.609358+00:00",
                "text": "Your insightful comment helps separate out two different arguments for why choice might improve schools, and points out that we would need to disentangle different types of evidence to determine if either point was true. This is why we did the exercise about labeling different choice arguments in class.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                "id": "eTBfPAVjS1-YcsL_vjErxA",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "KIfsXuq1SD-klJrd4piYhQ"
                ],
                "updated": "2015-02-05T15:00:13.145204+00:00",
                "created": "2015-02-05T15:00:13.145174+00:00",
                "text": "Continue to raise this point as we dig further into research on magnets and charters, as very few studies have asked what happens inside these schools.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "hL1TVLJlRAaf1izyo0X4cA",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "nDY8xQHxSyueFpfO3F9yWg"
                ],
                "updated": "2015-02-05T14:57:18.682452+00:00",
                "created": "2015-02-05T14:57:18.682419+00:00",
                "text": "I've never thought about the \"politics of respectability\" in the context of school choice advocacy. You're definitely making me think. . .",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "jvwtjmplRoudgfJdi7a1hw",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "TbIwVvC5QSmZ-ZgkDf16rQ"
                ],
                "updated": "2015-02-05T14:55:54.411827+00:00",
                "created": "2015-02-05T14:55:54.411795+00:00",
                "text": "Perhaps I should only give (intrinsic) comments rather than (extrinsic) grades?",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "p7UyP_1eSHqS--oABpb9RA",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "fzVKkQnyR5m_xWiwzMDxTg"
                ],
                "updated": "2015-02-05T14:54:21.742982+00:00",
                "created": "2015-02-05T14:54:21.742951+00:00",
                "text": "You've identified the core of Fuller's argument. During the 1960s, he protested in favor of school integration, and civil rights activists finally forced Milwaukee to begin doing this in the 1970s with magnet schools. But in the 1980s, Fuller objected that Milwaukee's magnet school plan protected White families and displaced Black ones, which led him to question who bears the burden of integration. That's the origin of his view that if Whites had choice (more access to desirable magnet schools), then Blacks should have choice, too (via vouchers).",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "jRxXpGtsT_ybe9sJz1fMxg",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "C_7851akS_mgiMnYDAYb0w"
                ],
                "updated": "2015-02-05T14:48:02.372791+00:00",
                "created": "2015-02-05T14:48:02.372760+00:00",
                "text": "Very interesting criticism of the consistency of Fuller's views on educational funding.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "k81fHClTQNGqAh4dT3VfMg",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "VxSyppivQGi5IrbMLuF0lQ"
                ],
                "updated": "2015-02-05T14:46:46.244877+00:00",
                "created": "2015-02-05T14:46:46.244852+00:00",
                "text": "Yes, you've identified a central idea here. But what it shows me is that Fuller and some of his conservative allies supported vouchers for very different reasons, so its \"original intent\" may have had different meanings to both sides.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "JoKY5JvEQ2SOX-xgHe_amg",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": "Global warming - Wikipedia, the free encyclopedia",
                  "link": [
                    {
                      "href": "http://en.wikipedia.org/wiki/Global_warming"
                    },
                    {
                      "href": "android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/Global_warming",
                      "rel": "alternate",
                      "type": ""
                    },
                    {
                      "href": "http://en.wikipedia.org/wiki/Global_warming",
                      "rel": "canonical",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "favicon": "http://bits.wikimedia.org/favicon/wikipedia.ico",
                  "dc": {},
                  "eprints": {},
                  "facebook": {},
                  "twitter": {}
                },
                "updated": "2015-02-05T14:45:34.430126+00:00",
                "created": "2015-02-05T14:45:34.430108+00:00",
                "text": "Nice",
                "permissions": {
                  "update": [
                    "acct:aron@stage.hypothes.is"
                  ],
                  "admin": [
                    "acct:aron@stage.hypothes.is"
                  ],
                  "delete": [
                    "acct:aron@stage.hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://en.wikipedia.org/wiki/Global_warming",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 33,
                        "startContainer": "/div[3]/div[3]/div[4]/p[23]/a[1]",
                        "startOffset": 0,
                        "type": "RangeSelector",
                        "endContainer": "/div[3]/div[3]/div[4]/p[23]"
                      },
                      {
                        "end": 18199,
                        "start": 18166,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "ainty in radiative forcing.[99]",
                        "type": "TextQuoteSelector",
                        "suffix": ", depending on whether it is air",
                        "exact": "Soot may cool or warm the surface"
                      },
                      {
                        "value": "#cite_note-4",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 14,
                      "top": 4263.515625
                    },
                    "source": "http://en.wikipedia.org/wiki/Global_warming"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "GUYjEWWQRRqvcs-kRCqVEg",
                "user": "acct:aron@stage.hypothes.is"
              },
              {
                "tags": [],
                "document": {
                  "prism": {},
                  "title": "",
                  "link": [
                    {
                      "href": "http://hypothes.is/"
                    },
                    {
                      "href": "https://hypothes.is/",
                      "rel": "canonical",
                      "type": ""
                    },
                    {
                      "href": "https://hypothes.is/?p=238",
                      "rel": "shortlink",
                      "type": ""
                    }
                  ],
                  "highwire": {},
                  "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                  "dc": {},
                  "eprints": {},
                  "facebook": {},
                  "twitter": {}
                },
                "updated": "2015-02-05T14:44:29.280672+00:00",
                "created": "2015-02-05T14:44:29.280655+00:00",
                "text": "Test",
                "permissions": {
                  "update": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "admin": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "delete": [
                    "acct:ujvari@stage.hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "http://hypothes.is/",
                "target": [
                  {
                    "selector": [
                      {
                        "endOffset": 10,
                        "startContainer": "/article[1]/article[1]/section[1]/p[1]",
                        "startOffset": 0,
                        "type": "RangeSelector",
                        "endContainer": "/article[1]/article[1]/section[1]/p[1]"
                      },
                      {
                        "end": 121,
                        "start": 111,
                        "type": "TextPositionSelector"
                      },
                      {
                        "prefix": "t Terms RSS The Web, Annotated.",
                        "type": "TextQuoteSelector",
                        "suffix": "y to announce the first version",
                        "exact": "We’re happ"
                      },
                      {
                        "value": "",
                        "type": "FragmentSelector"
                      }
                    ],
                    "pos": {
                      "height": 20,
                      "top": 233
                    },
                    "source": "http://hypothes.is/"
                  }
                ],
                "consumer": "00000000-0000-0000-0000-000000000000",
                "id": "GdjixL-wRr2Zw5zcV3GirQ",
                "user": "acct:ujvari@stage.hypothes.is"
              },
              {
                "tags": [],
                "references": [
                  "1HPi7v8zQ-e43oGgvVh0ww"
                ],
                "updated": "2015-02-05T14:42:34.904200+00:00",
                "created": "2015-02-05T14:42:34.904174+00:00",
                "text": "Glad to see you draw a connection to sources outside of our syllabus, but there's a key distinction that's missing here. The 1960s Milwaukee lawsuit charged that the school system racially segregated African-American students. The 2007 Seattle/Louisville cases charged that those districts, which voluntarily desegregated, had racially discriminated against White students. The plaintiffs prevailed in both cases, and the Court ruled that school districts may use race-conscious policies to promote integration, but only by looking at the racial composition of large areas (neighborhoods, etc.), not individual students.",
                "permissions": {
                  "update": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "admin": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "delete": [
                    "acct:JackDougherty@hypothes.is"
                  ],
                  "read": [
                    "group:__world__"
                  ]
                },
                "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                "id": "dj59zs25TNSFj50bd40YGg",
                "consumer": "00000000-0000-0000-0000-000000000000",
                "user": "acct:JackDougherty@hypothes.is"
              }
            ]

### Annotation List [GET]
Returns the most recent 20 annotations

+ Response 200 (application/json)

    [Annotation Collection][]

### Create an Annotation [POST]
+ Request (application/json)

        {
          "tags": [],
          "text": "The 5 \"encouraging facts\" about climate change the author mentions are:\n\n> in the previous 15 years [...] we’re seeing about 90% less temperature rise than expected\n\n> Antarctic sea ice [...] is increasing\n\n> sea levels are rising, but the rise is not accelerating\n\n> a decrease in the world’s surface that has been afflicted by droughts since 1982\n\n> the trend for landfalling typhoons around the Philippines has declined \n",
          "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
          "consumer": "00000000-0000-0000-0000-000000000000",
          "user": "acct:emvincent@hypothes.is"
        }

+ Response 201 (application/json)

        {
          "tags": [],
          "references": [
            "iHNf1mBeTrS0ClW_2rF3Iw"
          ],
          "updated": "2015-02-05T16:54:00.156927+00:00",
          "created": "2015-02-05T15:54:59.597989+00:00",
          "text": "The 5 \"encouraging facts\" about climate change the author mentions are:\n\n> in the previous 15 years [...] we’re seeing about 90% less temperature rise than expected\n\n> Antarctic sea ice [...] is increasing\n\n> sea levels are rising, but the rise is not accelerating\n\n> a decrease in the world’s surface that has been afflicted by droughts since 1982\n\n> the trend for landfalling typhoons around the Philippines has declined \n",
          "permissions": {
            "update": [
              "acct:emvincent@hypothes.is"
            ],
            "admin": [
              "acct:emvincent@hypothes.is"
            ],
            "delete": [
              "acct:emvincent@hypothes.is"
            ],
            "read": [
              "group:__world__"
            ]
          },
          "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
          "id": "LM-oVYS-TvauHw7bLK7XTw",
          "consumer": "00000000-0000-0000-0000-000000000000",
          "user": "acct:emvincent@hypothes.is"
        }

## Annotation [/api/annotations/{id}]
A single Annotation object with all its details

+ Parameters
    + id (required, string) ... `id` of the Annotation to perform action with. Has example value.

+ Model (application/json)

    JSON representation of a single annotation.

    + Body

            {
              "tags": [],
              "references": [
                "iHNf1mBeTrS0ClW_2rF3Iw"
              ],
              "updated": "2015-02-05T16:54:00.156927+00:00",
              "created": "2015-02-05T15:54:59.597989+00:00",
              "text": "The 5 \"encouraging facts\" about climate change the author mentions are:\n\n> in the previous 15 years [...] we’re seeing about 90% less temperature rise than expected\n\n> Antarctic sea ice [...] is increasing\n\n> sea levels are rising, but the rise is not accelerating\n\n> a decrease in the world’s surface that has been afflicted by droughts since 1982\n\n> the trend for landfalling typhoons around the Philippines has declined \n",
              "permissions": {
                "update": [
                  "acct:emvincent@hypothes.is"
                ],
                "admin": [
                  "acct:emvincent@hypothes.is"
                ],
                "delete": [
                  "acct:emvincent@hypothes.is"
                ],
                "read": [
                  "group:__world__"
                ]
              },
              "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
              "id": "LM-oVYS-TvauHw7bLK7XTw",
              "consumer": "00000000-0000-0000-0000-000000000000",
              "user": "acct:emvincent@hypothes.is"
            }

### Retrieve an Annotation [GET]
+ Response 200 (application/json)

    [Annotation][]

### Update an Annotation [PUT]
+ Request (application/json)

    [Annotation][]

+ Response 204

### Remove an Annotation [DELETE]
+ Response 204

## Search Annotations [/api/search{?limit,uri,user,quote,text}]
Search the primary annotations index.

+ Parameters
    + limit (optional, string) ... number of results to return
    + uri (optional, string) ... url encoded uri to get annotations for
    + user (optional, string) ... get annotations for a particular user.
    + quote (optional, string) ... words that the annotation is quoting.
    + text (optional, string) ... search annotation text.

### Retrieve Search Results [GET]
+ Response 200 (application/json)

            {
                "total": 8792,
                "rows": [
                  {
                    "tags": [],
                    "references": [
                      "iHNf1mBeTrS0ClW_2rF3Iw"
                    ],
                    "updated": "2015-02-05T16:54:00.156927+00:00",
                    "created": "2015-02-05T15:54:59.597989+00:00",
                    "text": "The 5 \"encouraging facts\" about climate change the author mentions are:\n\n> in the previous 15 years [...] we’re seeing about 90% less temperature rise than expected\n\n> Antarctic sea ice [...] is increasing\n\n> sea levels are rising, but the rise is not accelerating\n\n> a decrease in the world’s surface that has been afflicted by droughts since 1982\n\n> the trend for landfalling typhoons around the Philippines has declined \n",
                    "permissions": {
                      "update": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "admin": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "delete": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                    "id": "LM-oVYS-TvauHw7bLK7XTw",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:emvincent@hypothes.is"
                  },
                  {
                    "tags": [
                      "reference needed"
                    ],
                    "document": {
                      "prism": {},
                      "title": [
                        "The Alarming Thing About Climate Alarmism"
                      ],
                      "link": [
                        {
                          "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                        },
                        {
                          "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                          "rel": "canonical",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "dc": {},
                      "eprints": {},
                      "facebook": {
                        "title": [
                          "The Alarming Thing About Climate Alarmism"
                        ],
                        "image": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                        ],
                        "description": [
                          "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                        ],
                        "url": [
                          "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                        ],
                        "image:width": [
                          "553"
                        ],
                        "locale": [
                          "en_US"
                        ],
                        "image:height": [
                          "369"
                        ],
                        "site_name": [
                          "WSJ"
                        ],
                        "type": [
                          "article"
                        ]
                      },
                      "twitter": {
                        "card": [
                          "summary_large_image"
                        ],
                        "title": [
                          "The Alarming Thing About Climate Alarmism"
                        ],
                        "image": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_D_20150201121817.jpg"
                        ],
                        "description": [
                          "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                        ],
                        "site": [
                          "@WSJ"
                        ],
                        "domain": [
                          "wsj.com"
                        ],
                        "image:src": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                        ]
                      }
                    },
                    "updated": "2015-02-05T16:52:50.441027+00:00",
                    "created": "2015-02-05T15:53:15.924190+00:00",
                    "text": "This is a strong claim; a strong reference would be needed to back it up.\nIn this article, the author provides 5 facts about the changing climate to back this assertion. This is far from sufficient to give credit to the author's claim, especially since several of these facts are only one aspect of the story, as shown by the scientists' comments below.\n\n",
                    "permissions": {
                      "update": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "admin": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "delete": [
                        "acct:emvincent@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 258,
                            "startContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]",
                            "startOffset": 217,
                            "type": "RangeSelector",
                            "endContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]"
                          },
                          {
                            "end": 587,
                            "start": 546,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "han expected. This ignores that",
                            "type": "TextQuoteSelector",
                            "suffix": ". The latest study from the Unit",
                            "exact": "much of the data are actually encouraging"
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 19,
                          "top": 442
                        },
                        "source": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "iHNf1mBeTrS0ClW_2rF3Iw",
                    "user": "acct:emvincent@hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": [
                        "The Alarming Thing About Climate Alarmism"
                      ],
                      "link": [
                        {
                          "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                        },
                        {
                          "href": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                          "rel": "canonical",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "dc": {},
                      "eprints": {},
                      "facebook": {
                        "title": [
                          "The Alarming Thing About Climate Alarmism"
                        ],
                        "image": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                        ],
                        "description": [
                          "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                        ],
                        "url": [
                          "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                        ],
                        "image:width": [
                          "553"
                        ],
                        "locale": [
                          "en_US"
                        ],
                        "image:height": [
                          "369"
                        ],
                        "type": [
                          "article"
                        ],
                        "site_name": [
                          "WSJ"
                        ]
                      },
                      "twitter": {
                        "card": [
                          "summary_large_image"
                        ],
                        "title": [
                          "The Alarming Thing About Climate Alarmism"
                        ],
                        "image": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_D_20150201121817.jpg"
                        ],
                        "description": [
                          "In The Wall Street Journal, Bjorn Lomborg writes that exaggerated, worst-case claims about climate change result in bad policy and they ignore a wealth of encouraging data."
                        ],
                        "site": [
                          "@WSJ"
                        ],
                        "domain": [
                          "wsj.com"
                        ],
                        "image:src": [
                          "http://si.wsj.net/public/resources/images/ED-AT234_lombor_G_20150201121817.jpg"
                        ]
                      }
                    },
                    "updated": "2015-02-05T16:39:21.987184+00:00",
                    "created": "2015-02-03T23:26:29.974141+00:00",
                    "text": "This is true but somewhat misleading. \nOne can find 15-year periods earlier in the record when temperatures went up somewhat faster than projected. ",
                    "permissions": {
                      "update": [
                        "acct:emanuel@hypothes.is"
                      ],
                      "admin": [
                        "acct:emanuel@hypothes.is"
                      ],
                      "delete": [
                        "acct:emanuel@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 426,
                            "startContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]",
                            "startOffset": 260,
                            "type": "RangeSelector",
                            "endContainer": "/div[2]/div[4]/div[3]/article[1]/div[1]/div[1]/div[1]/div[1]/p[1]"
                          },
                          {
                            "end": 755,
                            "start": 589,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "data are actually encouraging.",
                            "type": "TextQuoteSelector",
                            "suffix": "The average of all models expec",
                            "exact": "The latest study from the United Nations Intergovernmental Panel on Climate Change found that in the previous 15 years temperatures had risen 0.09 degrees Fahrenheit."
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 47,
                          "top": 442
                        },
                        "source": "http://www.wsj.com/articles/bjorn-lomborg-the-alarming-thing-about-climate-alarmism-1422832462"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "chAmdc_eQf-hSDKKzC5NuQ",
                    "user": "acct:emanuel@hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": [
                        "Wer ist Pegida?: Dürfen wir vorstellen: Die Freunde von Pegida"
                      ],
                      "link": [
                        {
                          "href": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                        },
                        {
                          "href": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten",
                          "rel": "canonical",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "favicon": "http://images.zeit.de/static/img/favicon.ico",
                      "dc": {},
                      "eprints": {},
                      "facebook": {
                        "title": [
                          "Wer ist Pegida?: Dürfen wir vorstellen: Die Freunde von Pegida"
                        ],
                        "image": [
                          "http://images.zeit.de/gesellschaft/2015-02/pegida-dresden/pegida-dresden-540x304.jpg"
                        ],
                        "description": [
                          "Wer bekennt sich zu Pegida? Keiner weiß es genau. Auf Facebook aber sprechen die Anhänger der Bewegung. Diese Grafiken zeigen, was Pegidisten ausmacht"
                        ],
                        "url": [
                          "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                        ],
                        "type": [
                          "article"
                        ],
                        "site_name": [
                          "ZEIT ONLINE"
                        ]
                      },
                      "twitter": {}
                    },
                    "updated": "2015-02-05T15:48:35.699828+00:00",
                    "created": "2015-02-05T15:48:35.699811+00:00",
                    "text": "testing this real quick",
                    "permissions": {
                      "update": [
                        "acct:fabianmu@hypothes.is"
                      ],
                      "admin": [
                        "acct:fabianmu@hypothes.is"
                      ],
                      "delete": [
                        "acct:fabianmu@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 26,
                            "startContainer": "/div[2]/div[2]/div[2]/div[1]/div[1]/p[1]",
                            "startOffset": 0,
                            "type": "RangeSelector",
                            "endContainer": "/div[2]/div[2]/div[2]/div[1]/div[1]/p[1]"
                          },
                          {
                            "end": 483,
                            "start": 457,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "stellen: Die Freunde von Pegida",
                            "type": "TextQuoteSelector",
                            "suffix": "? Keiner weiß es genau. Auf Face",
                            "exact": "Wer bekennt sich zu Pegida"
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 25,
                          "top": 333
                        },
                        "source": "http://www.zeit.de/gesellschaft/zeitgeschehen/2015-02/wer-ist-pegida-facebook-daten"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "nLetVBXJReC1oZFaKIiN-A",
                    "user": "acct:fabianmu@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "rsMTUkq5SqaqPq4frw6rVA",
                      "h5ZKl5MyQGiChvMvLHrWIQ",
                      "MMRtCKbZQw6xJ9Je9mw6oA"
                    ],
                    "updated": "2015-02-05T15:27:30.278992+00:00",
                    "created": "2015-02-05T15:27:30.278960+00:00",
                    "text": "Thanks for your reply.  (See https://hypothes.is/a/8DBwmnIhQ5mNY_qwZ7IbJQ.)  Given your passion for the subject, I encourage you to post also in the NYT comments.",
                    "permissions": {
                      "update": [
                        "acct:rdhyee@hypothes.is"
                      ],
                      "admin": [
                        "acct:rdhyee@hypothes.is"
                      ],
                      "delete": [
                        "acct:rdhyee@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://well.blogs.nytimes.com/2015/02/03/new-york-attorney-general-targets-supplements-at-major-retailers/?hp&action=click&pgtype=Homepage&module=first-column-region&region=top-news&WT.nav=top-news&_r=0",
                    "id": "JMOvXYPfTQ6tmrvS1Mq8kA",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:rdhyee@hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": "",
                      "link": [
                        {
                          "href": "http://hypothes.is/"
                        },
                        {
                          "href": "https://hypothes.is/",
                          "rel": "canonical",
                          "type": ""
                        },
                        {
                          "href": "https://hypothes.is/?p=238",
                          "rel": "shortlink",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                      "dc": {},
                      "eprints": {},
                      "facebook": {},
                      "twitter": {}
                    },
                    "updated": "2015-02-05T15:15:18.080929+00:00",
                    "created": "2015-02-05T15:15:18.080897+00:00",
                    "text": "Teeees",
                    "permissions": {
                      "update": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "admin": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "delete": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://hypothes.is/",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 10,
                            "startContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]",
                            "startOffset": 0,
                            "type": "RangeSelector",
                            "endContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]"
                          },
                          {
                            "end": 2497,
                            "start": 2487,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "th in-situ feedback about th...",
                            "type": "TextQuoteSelector",
                            "suffix": "Google Analytics Typekit by Ado",
                            "exact": "Read more…"
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 18,
                          "top": 2057.600003051758
                        },
                        "source": "http://hypothes.is/"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "iiuopaJOSp6mLqy3FN66iw",
                    "user": "acct:ujvari@stage.hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": "",
                      "link": [
                        {
                          "href": "http://hypothes.is/"
                        },
                        {
                          "href": "https://hypothes.is/",
                          "rel": "canonical",
                          "type": ""
                        },
                        {
                          "href": "https://hypothes.is/?p=238",
                          "rel": "shortlink",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                      "dc": {},
                      "eprints": {},
                      "facebook": {},
                      "twitter": {}
                    },
                    "updated": "2015-02-05T15:11:55.455988+00:00",
                    "created": "2015-02-05T15:11:55.455971+00:00",
                    "text": "Atom teszt",
                    "permissions": {
                      "update": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "admin": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "delete": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://hypothes.is/",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 10,
                            "startContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]",
                            "startOffset": 0,
                            "type": "RangeSelector",
                            "endContainer": "/article[1]/article[1]/section[6]/ul[1]/li[4]/p[2]/a[1]"
                          },
                          {
                            "end": 2497,
                            "start": 2487,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "th in-situ feedback about th...",
                            "type": "TextQuoteSelector",
                            "suffix": "Google Analytics Typekit by Ado",
                            "exact": "Read more…"
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 18,
                          "top": 2057.6
                        },
                        "source": "http://hypothes.is/"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "X1B654lxS_uegUvc7dol5A",
                    "user": "acct:ujvari@stage.hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "MVnP035EQ02sRmgnW5Xs9w"
                    ],
                    "updated": "2015-02-05T15:11:26.575324+00:00",
                    "created": "2015-02-05T15:11:26.575292+00:00",
                    "text": "Interesting that both you and Nairi asked \"how can we fix the parent info problem?\" This is what I was thinking a few years ago when my Trinity collaborators and I created the \"SmartChoices\" school search tool and researched how parents used and interpreted it. We'll read it later this semester.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                    "id": "3v4FzkdPRbiV9L0geCJZmQ",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "Rj1pW-BWSBSPuMCY3LtExQ"
                    ],
                    "updated": "2015-02-05T15:10:57.045959+00:00",
                    "created": "2015-02-05T15:10:57.045927+00:00",
                    "text": "Interesting that both you and Rachel asked \"how can we fix the parent info problem\"? This is what I was thinking a few years ago when my Trinity collaborators and I created the \"SmartChoices\" school search tool and researched how parents used and interpreted it. We'll read it later this semester.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                    "id": "4AxZec3hRPuj9alVWWt9qQ",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "S_462UK5Tdq-1ARY_zRCRg"
                    ],
                    "updated": "2015-02-05T15:07:18.607194+00:00",
                    "created": "2015-02-05T15:07:18.607165+00:00",
                    "text": "Great way to reframe the question here. You're making me think more deeply about Lubienski's chapter.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                    "id": "sLADPndUSKa0Ucq0-jhgaw",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "2hxqJSZ2Qu6P7ZTJG6oW2Q"
                    ],
                    "updated": "2015-02-05T15:05:04.609382+00:00",
                    "created": "2015-02-05T15:05:04.609358+00:00",
                    "text": "Your insightful comment helps separate out two different arguments for why choice might improve schools, and points out that we would need to disentangle different types of evidence to determine if either point was true. This is why we did the exercise about labeling different choice arguments in class.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:a1c31a3c975c3d90ca0ea299760f1b0",
                    "id": "eTBfPAVjS1-YcsL_vjErxA",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "KIfsXuq1SD-klJrd4piYhQ"
                    ],
                    "updated": "2015-02-05T15:00:13.145204+00:00",
                    "created": "2015-02-05T15:00:13.145174+00:00",
                    "text": "Continue to raise this point as we dig further into research on magnets and charters, as very few studies have asked what happens inside these schools.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "hL1TVLJlRAaf1izyo0X4cA",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "nDY8xQHxSyueFpfO3F9yWg"
                    ],
                    "updated": "2015-02-05T14:57:18.682452+00:00",
                    "created": "2015-02-05T14:57:18.682419+00:00",
                    "text": "I've never thought about the \"politics of respectability\" in the context of school choice advocacy. You're definitely making me think. . .",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "jvwtjmplRoudgfJdi7a1hw",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "TbIwVvC5QSmZ-ZgkDf16rQ"
                    ],
                    "updated": "2015-02-05T14:55:54.411827+00:00",
                    "created": "2015-02-05T14:55:54.411795+00:00",
                    "text": "Perhaps I should only give (intrinsic) comments rather than (extrinsic) grades?",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "p7UyP_1eSHqS--oABpb9RA",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "fzVKkQnyR5m_xWiwzMDxTg"
                    ],
                    "updated": "2015-02-05T14:54:21.742982+00:00",
                    "created": "2015-02-05T14:54:21.742951+00:00",
                    "text": "You've identified the core of Fuller's argument. During the 1960s, he protested in favor of school integration, and civil rights activists finally forced Milwaukee to begin doing this in the 1970s with magnet schools. But in the 1980s, Fuller objected that Milwaukee's magnet school plan protected White families and displaced Black ones, which led him to question who bears the burden of integration. That's the origin of his view that if Whites had choice (more access to desirable magnet schools), then Blacks should have choice, too (via vouchers).",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "jRxXpGtsT_ybe9sJz1fMxg",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "C_7851akS_mgiMnYDAYb0w"
                    ],
                    "updated": "2015-02-05T14:48:02.372791+00:00",
                    "created": "2015-02-05T14:48:02.372760+00:00",
                    "text": "Very interesting criticism of the consistency of Fuller's views on educational funding.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "k81fHClTQNGqAh4dT3VfMg",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "VxSyppivQGi5IrbMLuF0lQ"
                    ],
                    "updated": "2015-02-05T14:46:46.244877+00:00",
                    "created": "2015-02-05T14:46:46.244852+00:00",
                    "text": "Yes, you've identified a central idea here. But what it shows me is that Fuller and some of his conservative allies supported vouchers for very different reasons, so its \"original intent\" may have had different meanings to both sides.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "JoKY5JvEQ2SOX-xgHe_amg",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": "Global warming - Wikipedia, the free encyclopedia",
                      "link": [
                        {
                          "href": "http://en.wikipedia.org/wiki/Global_warming"
                        },
                        {
                          "href": "android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/Global_warming",
                          "rel": "alternate",
                          "type": ""
                        },
                        {
                          "href": "http://en.wikipedia.org/wiki/Global_warming",
                          "rel": "canonical",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "favicon": "http://bits.wikimedia.org/favicon/wikipedia.ico",
                      "dc": {},
                      "eprints": {},
                      "facebook": {},
                      "twitter": {}
                    },
                    "updated": "2015-02-05T14:45:34.430126+00:00",
                    "created": "2015-02-05T14:45:34.430108+00:00",
                    "text": "Nice",
                    "permissions": {
                      "update": [
                        "acct:aron@stage.hypothes.is"
                      ],
                      "admin": [
                        "acct:aron@stage.hypothes.is"
                      ],
                      "delete": [
                        "acct:aron@stage.hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://en.wikipedia.org/wiki/Global_warming",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 33,
                            "startContainer": "/div[3]/div[3]/div[4]/p[23]/a[1]",
                            "startOffset": 0,
                            "type": "RangeSelector",
                            "endContainer": "/div[3]/div[3]/div[4]/p[23]"
                          },
                          {
                            "end": 18199,
                            "start": 18166,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "ainty in radiative forcing.[99]",
                            "type": "TextQuoteSelector",
                            "suffix": ", depending on whether it is air",
                            "exact": "Soot may cool or warm the surface"
                          },
                          {
                            "value": "#cite_note-4",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 14,
                          "top": 4263.515625
                        },
                        "source": "http://en.wikipedia.org/wiki/Global_warming"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "GUYjEWWQRRqvcs-kRCqVEg",
                    "user": "acct:aron@stage.hypothes.is"
                  },
                  {
                    "tags": [],
                    "document": {
                      "prism": {},
                      "title": "",
                      "link": [
                        {
                          "href": "http://hypothes.is/"
                        },
                        {
                          "href": "https://hypothes.is/",
                          "rel": "canonical",
                          "type": ""
                        },
                        {
                          "href": "https://hypothes.is/?p=238",
                          "rel": "shortlink",
                          "type": ""
                        }
                      ],
                      "highwire": {},
                      "favicon": "http://hypothes.is/wp-content/themes/hypothesis-1.0.11/favicon.ico",
                      "dc": {},
                      "eprints": {},
                      "facebook": {},
                      "twitter": {}
                    },
                    "updated": "2015-02-05T14:44:29.280672+00:00",
                    "created": "2015-02-05T14:44:29.280655+00:00",
                    "text": "Test",
                    "permissions": {
                      "update": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "admin": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "delete": [
                        "acct:ujvari@stage.hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "http://hypothes.is/",
                    "target": [
                      {
                        "selector": [
                          {
                            "endOffset": 10,
                            "startContainer": "/article[1]/article[1]/section[1]/p[1]",
                            "startOffset": 0,
                            "type": "RangeSelector",
                            "endContainer": "/article[1]/article[1]/section[1]/p[1]"
                          },
                          {
                            "end": 121,
                            "start": 111,
                            "type": "TextPositionSelector"
                          },
                          {
                            "prefix": "t Terms RSS The Web, Annotated.",
                            "type": "TextQuoteSelector",
                            "suffix": "y to announce the first version",
                            "exact": "We’re happ"
                          },
                          {
                            "value": "",
                            "type": "FragmentSelector"
                          }
                        ],
                        "pos": {
                          "height": 20,
                          "top": 233
                        },
                        "source": "http://hypothes.is/"
                      }
                    ],
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "id": "GdjixL-wRr2Zw5zcV3GirQ",
                    "user": "acct:ujvari@stage.hypothes.is"
                  },
                  {
                    "tags": [],
                    "references": [
                      "1HPi7v8zQ-e43oGgvVh0ww"
                    ],
                    "updated": "2015-02-05T14:42:34.904200+00:00",
                    "created": "2015-02-05T14:42:34.904174+00:00",
                    "text": "Glad to see you draw a connection to sources outside of our syllabus, but there's a key distinction that's missing here. The 1960s Milwaukee lawsuit charged that the school system racially segregated African-American students. The 2007 Seattle/Louisville cases charged that those districts, which voluntarily desegregated, had racially discriminated against White students. The plaintiffs prevailed in both cases, and the Court ruled that school districts may use race-conscious policies to promote integration, but only by looking at the racial composition of large areas (neighborhoods, etc.), not individual students.",
                    "permissions": {
                      "update": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "admin": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "delete": [
                        "acct:JackDougherty@hypothes.is"
                      ],
                      "read": [
                        "group:__world__"
                      ]
                    },
                    "uri": "urn:x-pdf:34a1939b5a3b4c4ba202bc13a971f",
                    "id": "dj59zs25TNSFj50bd40YGg",
                    "consumer": "00000000-0000-0000-0000-000000000000",
                    "user": "acct:JackDougherty@hypothes.is"
                  }
                ]
            }
