name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.cookiecutter/*'
      - '.github/*'
      - 'bin/create-testdb'
      - 'bin/install-python'
      - 'conf/development.ini'
      - 'conf/supervisord-dev.conf'
      - 'conf/websocket-dev.ini'
      - 'docs/*'
      - 'requirements/*'
      - '!requirements/prod.txt'
      - 'tests/*'
      - '.coveragerc'
      - '.eslintrc'
      - '.gitignore'
      - '.isort.cfg'
      - '.pylintrc'
      - 'HACKING.md'
      - 'LICENSE'
      - 'README.rst'
      - 'docker-compose.yml'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'tox.ini'
jobs:
  docker_hub:
    name: Docker Hub
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: hypothesis
    secrets: inherit
  staging:
    name: Staging
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Staging
      github_environment_url: https://staging.hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: staging
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  staging_websocket:
    name: Staging (WebSocket)
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Staging (WebSocket)
      github_environment_url: https://staging.hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: staging
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  production:
    name: Production
    needs: [docker_hub, staging, staging_websocket]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  production_websocket:
    name: Production (WebSocket)
    needs: [docker_hub, staging, staging_websocket]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (WebSocket)
      github_environment_url: https://hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
  production_canada:
    name: Production (Canada)
    needs: [docker_hub, staging, staging_websocket]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      github_environment_url: https://ca.hypothes.is/search
      aws_region: ca-central-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
