name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: hypothesis
    secrets: inherit

  qa:
    needs: create-image
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      github_environment_url: https://qa.hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  qa-websocket:
    needs: create-image
    name: qa-websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA (WebSocket)
      github_environment_url: https://qa.hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod:
    needs: [create-image, qa]
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-websocket:
    needs: [create-image, qa-websocket]
    name: prod-websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (WebSocket)
      github_environment_url: https://hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  prod-ca-central-1:
    needs: [create-image, qa]
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      github_environment_url: https://ca.hypothes.is/search
      aws_region: ca-central-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit
