name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  Docker_Hub:
    name: Docker Hub
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: hypothesis
    secrets: inherit

  QA:
    needs: Docker_Hub
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      github_environment_url: https://qa.hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  QA_WebSocket:
    needs: Docker_Hub
    name: QA (WebSocket)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA (WebSocket)
      github_environment_url: https://qa.hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production:
    needs: [Docker_Hub, QA]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production_WebSocket:
    needs: [Docker_Hub, QA_WebSocket]
    name: Production (WebSocket)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (WebSocket)
      github_environment_url: https://hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  Production_Canada:
    needs: [Docker_Hub, QA]
    name: Production (Canada)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      github_environment_url: https://ca.hypothes.is/search
      aws_region: ca-central-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
