name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      staging:
        type: boolean
        description: Redeploy Staging
      staging_websocket:
        type: boolean
        description: Redeploy Staging (WebSocket)
      production:
        type: boolean
        description: Redeploy Production
      production_websocket:
        type: boolean
        description: Redeploy Production (WebSocket)
      production_canada:
        type: boolean
        description: Redeploy Production (Canada)
jobs:
  staging:
    name: Staging
    if: inputs.staging
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging
      github_environment_url: https://staging.hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: staging
    secrets: inherit
  staging_websocket:
    name: Staging (WebSocket)
    if: inputs.staging_websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging (WebSocket)
      github_environment_url: https://staging.hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: staging
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_websocket:
    name: Production (WebSocket)
    if: inputs.production_websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (WebSocket)
      github_environment_url: https://hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_canada:
    name: Production (Canada)
    if: inputs.production_canada
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Canada)
      github_environment_url: https://ca.hypothes.is/search
      aws_region: ca-central-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
    secrets: inherit
