name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      qa:
        type: boolean
        description: Redeploy QA
      qa_websocket:
        type: boolean
        description: Redeploy QA (WebSocket)
      production:
        type: boolean
        description: Redeploy Production
      production_websocket:
        type: boolean
        description: Redeploy Production (WebSocket)
      production_canada:
        type: boolean
        description: Redeploy Production (Canada)
jobs:
  qa:
    name: QA
    if: inputs.qa
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA
      github_environment_url: https://qa.hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: qa
    secrets: inherit
  qa_websocket:
    name: QA (WebSocket)
    if: inputs.qa_websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: QA (WebSocket)
      github_environment_url: https://qa.hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: qa
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://hypothes.is/search
      aws_region: us-west-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_websocket:
    name: Production (WebSocket)
    if: inputs.production_websocket
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (WebSocket)
      github_environment_url: https://hypothes.is/docs/help
      aws_region: us-west-1
      elasticbeanstalk_application: h-websocket
      elasticbeanstalk_environment: prod
    secrets: inherit
  production_canada:
    name: Production (Canada)
    if: inputs.production_canada
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production (Canada)
      github_environment_url: https://ca.hypothes.is/search
      aws_region: ca-central-1
      elasticbeanstalk_application: h
      elasticbeanstalk_environment: prod
    secrets: inherit
