name: Slack
on:
  workflow_run:
    workflows: [CI, Deploy]
    types: [completed]
    branches: [main]
jobs:
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Post to Slack
    uses: hypothesis/workflows/.github/workflows/slack.yml@main
    with:
      payload: |
        channel: "C4K6M7P5E"
        markdown_text: "Failed `${{ github.event.workflow_run.path }}` run (attempt ${{ github.event.workflow_run.run_attempt }}) on `${{ github.event.workflow_run.head_branch }}` in `${{ github.event.workflow_run.repository.full_name }}`: ${{ github.event.workflow_run.html_url }}"
    secrets: inherit
